import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";

// import { cookieToInitialState } from "wagmi";
// import Web3ModalProvider from "@/context";

import { cookieToInitialState } from "@alchemy/aa-alchemy/config";
import { config } from "@/config/alchemy";
import { Providers } from "@/context/alchemy";

export const metadata: Metadata = {
  title: "Chatter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    config,
    headers().get("cookie") || undefined
  );

  return (
    <html lang="en">
      <body>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  );
}
